// ─── Database types ────────────────────────────────────────────────────────────
// These types are auto-generated by Supabase.
// Run `npm run db:types` to regenerate after schema changes.
// This file provides hand-written types for initial development.
// Once Supabase is linked, `npm run db:types` will output to database.types.ts
// and this file can be replaced with the generated one.

export type UserRole = "customer" | "worker" | "both";

export interface Profile {
  id: string;
  display_name: string;
  avatar_url: string | null;
  role: UserRole;
  phone: string | null;
  is_verified: boolean;
  created_at: string;
}

export interface Trade {
  id: number;
  slug: string;
  name: string;
}

export interface WorkerProfile {
  profile_id: string;
  bio: string | null;
  hourly_rate: number | null;
  location: string | null; // PostGIS geography point (GeoJSON)
  is_available: boolean;
  rating: number;
}

export interface WorkerTrade {
  worker_id: string;
  trade_id: number;
}

export type ListingStatus = "open" | "awarded" | "in_progress" | "done" | "cancelled";

export interface Listing {
  id: string;
  customer_id: string;
  title: string;
  description: string | null;
  trade_id: number | null;
  budget: number | null;
  status: ListingStatus;
  location: string | null;
  search_vector: string | null;
  created_at: string;
}

export type BidStatus = "pending" | "accepted" | "rejected";

export interface Bid {
  id: string;
  listing_id: string;
  worker_id: string;
  amount: number;
  message: string | null;
  status: BidStatus;
  created_at: string;
}

export type BookingStatus = "scheduled" | "in_progress" | "completed" | "cancelled" | "disputed";

export interface Booking {
  id: string;
  listing_id: string | null;
  customer_id: string;
  worker_id: string;
  status: BookingStatus;
  scheduled_at: string | null;
  final_price: number | null;
  created_at: string;
}

export interface Review {
  id: string;
  booking_id: string;
  author_id: string;
  subject_id: string;
  rating: number;
  body: string | null;
  created_at: string;
}

export interface Message {
  id: string;
  booking_id: string;
  sender_id: string;
  body: string;
  created_at: string;
}

export type PaymentDirection = "in" | "out";
export type PaymentStatus = "pending" | "captured" | "paid_out" | "refunded" | "failed";

export interface PaymentLedger {
  id: string;
  booking_id: string | null;
  actor_id: string | null;
  direction: PaymentDirection;
  amount: number;
  currency: string;
  provider: string | null;
  provider_charge_id: string | null;
  status: PaymentStatus;
  created_at: string;
}

// ─── Nearby workers RPC result ─────────────────────────────────────────────────

export interface NearbyWorker {
  profile_id: string;
  display_name: string;
  avatar_url: string | null;
  hourly_rate: number | null;
  rating: number;
  distance_km: number;
}
